### PR TITLE
Minor tweaks for readability

### PR DESCRIPTION
**Pull request by d4nyll**
Good write-up!

I saw an 'of' missing in the sentence 'If you find yourself in need a morale boost'. The rest of the changes are a little subjective but I think they make the sentences read off the tongue better. WDYT?

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Nice work on finding those typos, and excellent grammar additions! Thank you so much for the perfect PR!

**Comment by jonschlinkert** [comment]
I wrote this so I would remember to follow the points in it. Now if I could come up with something to remind me to remember, I'll be in great shape!

**Comment by d4nyll** [comment]
Yeah I saw your tweet about people taking your work, made some superficial changes, and rebranded as their own. I was so surprised that this sort of things happen in the OS community.

But then I saw your pinned tweet, and thought "Maybe a PR would help you remember your own tips!"

Anyways. There'll always be fakes, trolls and (real) imposters. Karma's a bitch, let her deal with them. What's most important are your family and close friends. Work hard for them - they are the only ones who will always appreciate you.

> If you can bear to hear the truth you’ve spoken
    Twisted by knaves to make a trap for fools,
Or watch the things you gave your life to, broken,
    And stoop and build ’em up with worn-out tools:
If you can fill the unforgiving minute
    With sixty seconds’ worth of distance run,   
Yours is the Earth and everything that’s in it,   
~ Some Rudyard Kipling dude

**Comment by jonschlinkert** [comment]
Thank you for this amazing, thoughtful and warm comment. It means the world to me. I think we should add that quote to the guide, so that anyone who reads it will be inspired by it like I am now. 

Would you like to do another PR? Moreover, would you like to add some of “you” to this guide? You have quite a way with words. I have no expectations or rules regarding what, how or if you contribute. It’s a work in progress, and I’m open to anything! 

Either way, thank you for the amazing words of encouragement!

**Comment by d4nyll** [comment]
Yeah I would like to do another PR. I think the part

> There'll always be fakes, trolls and (real) imposters. Karma's a bitch, let her deal with them. What's most important are your family and close friends. Work hard for them - they are the only ones who will always appreciate you.

and the Kipling quote is a good addition.

I'd like to contribute more but I don't think I have enough experience maintaining projects and dealing with negative comments for my 'advice' to be 'real'. But I'll keep this repo at the back of my mind. Whenever I come up with something, you'll find yourself another PR!

**Pull request merged**
